<a href="https://colab.research.google.com/github/UktamSam/AI_Foundation/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [5]:
print(pd.__version__)

2.2.2

In [8]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Ferrari", "RR", "KIA", "Genesis"],
  'counts': [3, 7, 2, 2, 1, 4, 9]
}
print('mydataset:',mydataset)

df = pd.DataFrame(mydataset)
print('df:', df)

mydataset: {'cars': ['BMW', 'Volvo', 'Ford', 'Ferrari', 'RR', 'KIA', 'Genesis'], 'counts': [3, 7, 2, 2, 1, 4, 9]}
df:       cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3  Ferrari       2
4       RR       1
5      KIA       4
6  Genesis       9

In [12]:
df.head() # default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3  Ferrari       2
4       RR       1

In [11]:
df.tail() # oxiridan 5 rows default

      cars  counts
2     Ford       2
3  Ferrari       2
4       RR       1
5      KIA       4
6  Genesis       9

In [13]:
df.shape # 7-row, 2-columns

(7, 2)

In [14]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [15]:
df.dtypes

cars      object
counts     int64
dtype: object

In [18]:
df.describe() # numerical columns only; std - raqamlar qanchalik uzoq bir birovidan

        counts
count  7.00000
mean   4.00000
std    2.94392
min    1.00000
25%    2.00000
50%    3.00000
75%    5.50000
max    9.00000

In [21]:
df.iloc[0:3] # index orqali malumotni chiqarib beradi.

    cars  counts
0    BMW       3
1  Volvo       7
2   Ford       2

In [24]:
df.loc[:, 'cars']

0        BMW
1      Volvo
2       Ford
3    Ferrari
4         RR
5        KIA
6    Genesis
Name: cars, dtype: object

In [26]:
df['counts']>5

0    False
1     True
2    False
3    False
4    False
5    False
6     True
Name: counts, dtype: bool

In [27]:
df[df['counts']>4]

      cars  counts
1    Volvo       7
6  Genesis       9

In [28]:
df.mean(numeric_only=True)

counts    4.0
dtype: float64

In [29]:
df.sum() #max, min, count, median, std

cars      BMWVolvoFordFerrariRRKIAGenesis
counts                                 28
dtype: object

In [31]:
data_with_missing = {
    "cars": ["BMW", "VOLVO", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 8, None, 8, 1, 9, None]
}
df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    VOLVO     8.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [32]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [33]:
df_missing.dropna() # how='all'; axis; subset=['counts']

      cars  counts
0      BMW     3.0
1    VOLVO     8.0
3    Tesla     8.0
4  Ferrari     1.0

In [35]:
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    VOLVO     8.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [38]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head(10)

# df = pd.read_excel("etwery.xlsx")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [39]:
df.to_excel("output.xlsx")

In [40]:
#Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ford"])
print('cars:', cars)

cars: 0      BMW
1    Tesla
2     Ford
dtype: object